// <auto-generated />
using System;
using KFTSDataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KFTSDataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250807122449_gelirIslemleri2")]
    partial class gelirIslemleri2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Gelir", b =>
                {
                    b.Property<int>("GelirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GelirId"));

                    b.Property<string>("GelirMiktar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurId")
                        .HasColumnType("int");

                    b.HasKey("GelirId");

                    b.HasIndex("TurId");

                    b.ToTable("Gelirs");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Gider", b =>
                {
                    b.Property<int>("GiderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiderId"));

                    b.Property<string>("GiderMiktar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurId")
                        .HasColumnType("int");

                    b.HasKey("GiderId");

                    b.HasIndex("TurId");

                    b.ToTable("Giders");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Kullanıcı", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("KullaniciAdiSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KullaniciOlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("KullaniciId");

                    b.HasIndex("RolId");

                    b.ToTable("Kullanıcıs");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Tur", b =>
                {
                    b.Property<int>("TurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurId"));

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TurId");

                    b.ToTable("Turs");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Varlik", b =>
                {
                    b.Property<int>("VarlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VarlikId"));

                    b.Property<int>("TurId")
                        .HasColumnType("int");

                    b.Property<string>("VarlikAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarlikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarlikFiyat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VarlikId");

                    b.HasIndex("TurId");

                    b.ToTable("Varlik");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Gelir", b =>
                {
                    b.HasOne("KFTSEntityLayer.Concrete.Tur", "Tur")
                        .WithMany("Gelirs")
                        .HasForeignKey("TurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tur");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Gider", b =>
                {
                    b.HasOne("KFTSEntityLayer.Concrete.Tur", "Tur")
                        .WithMany("Giders")
                        .HasForeignKey("TurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tur");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Kullanıcı", b =>
                {
                    b.HasOne("KFTSEntityLayer.Concrete.Rol", "Rol")
                        .WithMany("Kullanıcıs")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Varlik", b =>
                {
                    b.HasOne("KFTSEntityLayer.Concrete.Tur", "Tur")
                        .WithMany("Varliks")
                        .HasForeignKey("TurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tur");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Rol", b =>
                {
                    b.Navigation("Kullanıcıs");
                });

            modelBuilder.Entity("KFTSEntityLayer.Concrete.Tur", b =>
                {
                    b.Navigation("Gelirs");

                    b.Navigation("Giders");

                    b.Navigation("Varliks");
                });
#pragma warning restore 612, 618
        }
    }
}
